#pragma once
#define CONFIG_H
#define WINDOW_MULTIPLIER 20
#define SCREEN_WIDTH 64
#define SCREEN_HEIGHT 32
#define CHIP8_MEMORY_SIZE 0x1000
#define CHIP8_WINDOW_MULTIPLIER 10
#define CHIP8_NUM_DATA_REGISTERS 0xf
#define CHIP8_TOTAL_STACK_DEPTH 0xf
#define CHIP8_TOTAL_KEYS 0xf
#define CHIP8_CHARACTER_SET_LOAD_ADDRESS 0x00